#!/usr/bin/env bash
set -euo pipefail

# create-kimi-credential-launcher.sh — generate a Kimi Code CLI launcher with an
# isolated KIMI_CODE_HOME, for hosting multiple OAuth credentials side by side.
# Generated launcher: <output-dir>/<name>, home: <home-dir> (default
# ~/kimi-homes/<name>). Login is separate: run "<name> login" after creation.

name=''
home_dir=''
output_dir="$HOME/.local/bin"
kimi_bin=''

usage() {
  cat >&2 <<'EOF'
Usage: create-kimi-credential-launcher.sh --name kimi-<suffix> [options]

Required:
  --name NAME       Launcher name, must match kimi-<suffix> (lowercase letters,
                    digits, hyphens; suffix must be non-empty).

Options:
  --home DIR        Data home for the launcher (default: ~/kimi-homes/<name>).
  --output DIR      Directory for the launcher file (default: ~/.local/bin).
  --kimi-bin PATH   Pin the kimi binary path (default: auto-detect at runtime).
  -h, --help        Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) name="${2:?--name requires a value}"; shift 2 ;;
    --home) home_dir="${2:?--home requires a value}"; shift 2 ;;
    --output) output_dir="${2:?--output requires a value}"; shift 2 ;;
    --kimi-bin) kimi_bin="${2:?--kimi-bin requires a value}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "create-kimi-credential-launcher: unknown option $1" >&2; usage; exit 2 ;;
  esac
done

if [[ -z "$name" ]]; then
  echo "create-kimi-credential-launcher: --name is required" >&2
  usage
  exit 2
fi
if [[ ! "$name" =~ ^kimi-[a-z0-9][a-z0-9-]*$ ]]; then
  echo "create-kimi-credential-launcher: --name must match kimi-<suffix> (got: $name)" >&2
  exit 2
fi
if [[ -z "$home_dir" ]]; then
  home_dir="$HOME/kimi-homes/$name"
fi
if [[ -n "$kimi_bin" && ! -x "$kimi_bin" ]]; then
  echo "create-kimi-credential-launcher: --kimi-bin is not executable: $kimi_bin" >&2
  exit 2
fi

mkdir -p "$output_dir"
launcher="$output_dir/$name"

pinned_kimi_line=''
if [[ -n "$kimi_bin" ]]; then
  pinned_kimi_line="kimi_bin='$kimi_bin'"
fi

cat > "$launcher" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Kimi Code launcher "$name" with an isolated data home, signed in via OAuth
# (kimi login device-code flow), independent of the default ~/.kimi-code.
# Generated by imsight-dev-box-init->coding-agent->kimi-multi-credential().
self_name="\$(basename "\$0")"
export KIMI_CODE_HOME="\${KIMI_HOME_OVERRIDE:-$home_dir}"
mkdir -p "\$KIMI_CODE_HOME"

$pinned_kimi_line
if [[ -z "\${kimi_bin:-}" ]]; then
  for candidate in "\$HOME/.kimi-code/bin/kimi" "\$HOME/.local/bin/kimi"; do
    if [[ -x "\$candidate" && "\$candidate" != "\$0" ]]; then
      kimi_bin="\$candidate"
      break
    fi
  done
fi
if [[ -z "\${kimi_bin:-}" ]]; then
  kimi_bin="\$(command -v kimi || true)"
fi
if [[ -z "\${kimi_bin:-}" ]]; then
  echo "\$self_name: kimi binary not found" >&2
  exit 127
fi

exec "\$kimi_bin" "\$@"
EOF

chmod +x "$launcher"
echo "created launcher: $launcher"
echo "data home:        $home_dir"
echo "next step:        $name login   # OAuth device-code flow"
